openapi: 3.0.0
info:
  title: Contacts API
  description: RESTful API for managing contacts
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /contacts:
    get:
      summary: Get all contacts
      parameters:
        - name: sortField
          in: query
          description: Field to sort by (e.g., name, gender, phone, email)
          schema:
            type: string
        - name: sortOrder
          in: query
          description: Sorting order (asc, desc)
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          description: Number of contacts per page for pagination
          schema:
            type: integer
            minimum: 1
            default: 10
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          description: Contact created successfully
        '400':
          description: Invalid request body
  /contacts/{id}:
    get:
      summary: Get a contact by ID
      parameters:
        - name: id
          required: true
          in: path
          description: Contact ID
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact not found
    put:
      summary: Update a contact
      parameters:
        - name: id
          required: true
          in: path
          description: Contact ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: Contact updated successfully
        '400':
          description: Invalid request body
        '404':
          description: Contact not found
    delete:
      summary: Delete a contact
      parameters:
        - name: id
          required: true
          in: path
          description: Contact ID
          schema:
            type: string
      responses:
        '204':
          description: Contact deleted successfully
        '404':
          description: Contact not found
components:
  schemas:
    Contact:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        gender:
          type: string
        phone:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
